name: Release Drafter

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: release-drafter/release-drafter@v6
        with:
          commitish: refs/heads/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
