name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
      - 'poetry.lock'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ./.github/workflows/poetry-composite-action
      - name: Run tests
        run: |
          poetry run pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov custom_components.state_webhook \
            --cov-report xml \
            -o console_output_style=count \
            -p no:sugar \
            tests
          poetry run coverage lcov
      - name: Upload Coverage Results
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
